# Generated by Django 2.0.2 on 2018-02-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20180211_2026'),
        ('events', '0002_auto_20180211_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.CharField(max_length=255)),
                ('guess', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(blank=True, null=True)),
                ('difference', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('dnf', 'did not finish'), ('dns', 'did not start'), ('dsq', 'disqualified')], max_length=3)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Entry')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'date')},
        ),
        migrations.AddField(
            model_name='klass',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='entry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='entry',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Klass'),
        ),
        migrations.AddField(
            model_name='entry',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='klass',
            unique_together={('name', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('bib', 'event'), ('person', 'klass')},
        ),
    ]
